services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dolgoletie:latest
    container_name: dolgoletie
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/app/data/data.db
      UPLOADS_DIR: /app/uploads
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
